// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdA779uLAHSpf94sh76Gxizz1o1o6jQhI',
    appId: '1:202465840134:web:2cd228a24a75e7400f0787',
    messagingSenderId: '202465840134',
    projectId: 'demand-ff258',
    authDomain: 'demand-ff258.firebaseapp.com',
    storageBucket: 'demand-ff258.appspot.com',
    measurementId: 'G-3G4NXP3MLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSSUfzUfwCIv5iZ9xusMB-X6DeRf4gig',
    appId: '1:202465840134:android:efe4b9f0a5362d8d0f0787',
    messagingSenderId: '202465840134',
    projectId: 'demand-ff258',
    storageBucket: 'demand-ff258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApIIgmAQUPv7XeJ8CUiuLmytCtv4sfpvM',
    appId: '1:202465840134:ios:0411dc44bd7b66870f0787',
    messagingSenderId: '202465840134',
    projectId: 'demand-ff258',
    storageBucket: 'demand-ff258.appspot.com',
    iosBundleId: 'demand.id.demand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApIIgmAQUPv7XeJ8CUiuLmytCtv4sfpvM',
    appId: '1:202465840134:ios:0411dc44bd7b66870f0787',
    messagingSenderId: '202465840134',
    projectId: 'demand-ff258',
    storageBucket: 'demand-ff258.appspot.com',
    iosBundleId: 'demand.id.demand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdA779uLAHSpf94sh76Gxizz1o1o6jQhI',
    appId: '1:202465840134:web:17f59040bd3c2a620f0787',
    messagingSenderId: '202465840134',
    projectId: 'demand-ff258',
    authDomain: 'demand-ff258.firebaseapp.com',
    storageBucket: 'demand-ff258.appspot.com',
    measurementId: 'G-2JEXY7864J',
  );
}
